# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nimo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["moonpxi"]
  s.date = %q{2009-09-17}
  s.email = %q{paulo.schneider@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/bouncy.rb",
     "examples/eventy.rb",
     "examples/images/dg_classm32.png",
     "examples/images/dg_dungeon32.png",
     "examples/images/jeeklabs.png",
     "examples/images/tcheco.png",
     "examples/imagey.rb",
     "examples/screeny.rb",
     "examples/simplest.rb",
     "examples/sounds/KDE-Sys-Log-Out.ogg",
     "examples/sounds/k3b_error1.wav",
     "examples/soundy.rb",
     "examples/spritey.rb",
     "lib/nimo.rb",
     "lib/nimo/behavior/deflector.rb",
     "lib/nimo/behavior/moveable.rb",
     "lib/nimo/behavior/projectile.rb",
     "lib/nimo/behavior/with_velocity.rb",
     "lib/nimo/game_object.rb",
     "lib/nimo/game_window.rb",
     "lib/nimo/listeners/event_listener.rb",
     "lib/nimo/listeners/input_listener.rb",
     "lib/nimo/representations/image_representation.rb",
     "lib/nimo/representations/object_representation.rb",
     "lib/nimo/representations/quad_representation.rb",
     "lib/nimo/representations/sprite_representation.rb",
     "lib/nimo/representations/text_representation.rb",
     "lib/nimo/screen.rb",
     "lib/nimo/utils/game.rb",
     "lib/nimo/utils/intersection.rb",
     "lib/nimo/utils/object_extension.rb",
     "lib/nimo/utils/resources.rb",
     "nimo.gemspec",
     "spec/nimo/behavior/deflector_spec.rb",
     "spec/nimo/behavior/moveable_spec.rb",
     "spec/nimo/behavior/projectile_spec.rb",
     "spec/nimo/behavior/with_velocity_spec.rb",
     "spec/nimo/game_object_spec.rb",
     "spec/nimo/game_window_spec.rb",
     "spec/nimo/listeners/event_listener_spec.rb",
     "spec/nimo/listeners/input_listener_spec.rb",
     "spec/nimo/representations/image_representation_spec.rb",
     "spec/nimo/representations/object_representation_spec.rb",
     "spec/nimo/representations/sprite_representation_spec.rb",
     "spec/nimo/representations/text_representation_spec.rb",
     "spec/nimo/screen_spec.rb",
     "spec/nimo/utils/game_spec.rb",
     "spec/nimo/utils/object_extension_spec.rb",
     "spec/nimo/utils/resources_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/moonpxi/nimo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Ruby game development library using Gosu.}
  s.test_files = [
    "spec/nimo/behavior/deflector_spec.rb",
     "spec/nimo/behavior/moveable_spec.rb",
     "spec/nimo/behavior/projectile_spec.rb",
     "spec/nimo/behavior/with_velocity_spec.rb",
     "spec/nimo/game_object_spec.rb",
     "spec/nimo/game_window_spec.rb",
     "spec/nimo/listeners/event_listener_spec.rb",
     "spec/nimo/listeners/input_listener_spec.rb",
     "spec/nimo/representations/image_representation_spec.rb",
     "spec/nimo/representations/object_representation_spec.rb",
     "spec/nimo/representations/sprite_representation_spec.rb",
     "spec/nimo/representations/text_representation_spec.rb",
     "spec/nimo/screen_spec.rb",
     "spec/nimo/utils/game_spec.rb",
     "spec/nimo/utils/object_extension_spec.rb",
     "spec/nimo/utils/resources_spec.rb",
     "spec/spec_helper.rb",
     "examples/bouncy.rb",
     "examples/eventy.rb",
     "examples/imagey.rb",
     "examples/screeny.rb",
     "examples/simplest.rb",
     "examples/soundy.rb",
     "examples/spritey.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
